### ISSUE TITLE
Init command doesn't work in SimpleLocalize 2.5.0

### ISSUE THREAD

**Issue by jpomykala** [simplelocalize/simplelocalize-cli#94]
**Describe the bug**
```
~ simplelocalize init
Command failed.
java.net.MalformedURLException: Accessing an URL protocol that was not enabled. The URL protocol https is supported but not enabled by default. It must be enabled by adding the --enable-url-protocols=https option to the native-image command.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.JavaNetSubstitutions.unsupported(JavaNetSubstitutions.java:254)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.JavaNetSubstitutions.getURLStreamHandler(JavaNetSubstitutions.java:228)
	at java.base@17.0.7/java.net.URL.getURLStreamHandler(URL.java:80)
	at java.base@17.0.7/java.net.URL.<init>(URL.java:680)
	at java.base@17.0.7/java.net.URL.fromURI(URL.java:748)
	at java.base@17.0.7/java.net.URI.toURL(URI.java:1139)
	at io.simplelocalize.cli.command.InitCommand.invoke(InitCommand.java:36)
	at io.simplelocalize.cli.SimplelocalizeCliCommand.init(SimplelocalizeCliCommand.java:380)
	at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2066)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.simplelocalize.cli.SimplelocalizeCliCommand.main(SimplelocalizeCliCommand.java:50)
```

**Comment by jpomykala** [comment]
It's fixed in https://github.com/simplelocalize/simplelocalize-cli/commit/2e42ff2f26463bf54ac1ddab049b3ed99cd24be4
